# File: backend/app/artifacts/generators.py
"""
Real artifact generators — produce actual .pptx/.docx/.xlsx files on disk.

Each generator is an adapter over one office library (python-pptx, python-docx,
openpyxl) consuming the library-agnostic ArtifactSpec and an ArtifactStyle.
Formatting comes from the style profile, so richer templates land without
touching generation logic. Adding a format = adding a generator + registry
entry. Correctness first; styling is applied defensively so it can never make
generation fragile.
"""

from __future__ import annotations

from pathlib import Path
from typing import Protocol

from app.artifacts.images import resolve_image
from app.artifacts.spec import ArtifactSpec
from app.artifacts.styles import ArtifactStyle, get_style


class ArtifactGenerator(Protocol):
    kind: str

    def write(self, spec: ArtifactSpec, path: Path, style: ArtifactStyle) -> Path: ...


class PptxArtifactGenerator:
    kind = "pptx"

    def write(self, spec: ArtifactSpec, path: Path, style: ArtifactStyle) -> Path:
        from pptx import Presentation
        from pptx.dml.color import RGBColor
        from pptx.util import Inches, Pt

        prs = Presentation()
        accent = RGBColor(*style.accent_rgb)

        for slide in spec.slides:
            layout = slide.layout
            if layout == "title":
                s = prs.slides.add_slide(prs.slide_layouts[0])
                s.shapes.title.text = slide.title or spec.title
                if len(s.placeholders) > 1:
                    s.placeholders[1].text = (slide.bullets[0] if slide.bullets else "Generated by AIRA-X")
                self._style_title(s.shapes.title, style.title_size_pt, accent)
                continue

            if layout == "section":
                s = prs.slides.add_slide(prs.slide_layouts[2])
                s.shapes.title.text = slide.title
                self._style_title(s.shapes.title, style.section_size_pt, accent)
                continue

            # agenda / content / summary all use the title+content layout.
            s = prs.slides.add_slide(prs.slide_layouts[1])
            s.shapes.title.text = slide.title
            self._style_title(s.shapes.title, style.slide_title_size_pt, accent)

            # Optional image: inserted only if a real local path resolved.
            image_path = slide.image_path or resolve_image(slide.image_query)
            if image_path:
                try:
                    s.shapes.add_picture(image_path, Inches(6.6), Inches(1.8), width=Inches(3.0))
                except Exception:
                    image_path = None  # never let a bad image break the slide

            body = s.placeholders[1].text_frame
            body.clear()
            body.word_wrap = True
            bullets = slide.bullets[: style.max_bullets_per_slide] or [""]
            for i, bullet in enumerate(bullets):
                para = body.paragraphs[0] if i == 0 else body.add_paragraph()
                para.text = bullet
                para.font.size = Pt(style.body_size_pt)
                para.space_after = Pt(8)

        path.parent.mkdir(parents=True, exist_ok=True)
        prs.save(str(path))
        return path

    @staticmethod
    def _style_title(shape, size_pt, color) -> None:
        from pptx.util import Pt

        try:
            for para in shape.text_frame.paragraphs:
                para.font.size = Pt(size_pt)
                para.font.bold = True
                para.font.color.rgb = color
        except Exception:
            pass  # styling is best-effort; never break generation


class DocxArtifactGenerator:
    kind = "docx"

    def write(self, spec: ArtifactSpec, path: Path, style: ArtifactStyle) -> Path:
        from docx import Document
        from docx.enum.text import WD_ALIGN_PARAGRAPH

        doc = Document()
        title = doc.add_heading(spec.title, level=0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        if spec.subtitle:
            sub = doc.add_paragraph(spec.subtitle)
            sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
            for run in sub.runs:
                run.italic = True

        for section in spec.sections:
            if section.heading:
                doc.add_heading(section.heading, level=min(section.level, 2) or 1)
            for paragraph in section.paragraphs:
                doc.add_paragraph(paragraph)
            for bullet in section.bullets:
                doc.add_paragraph(bullet, style="List Bullet")

        path.parent.mkdir(parents=True, exist_ok=True)
        doc.save(str(path))
        return path


class XlsxArtifactGenerator:
    kind = "xlsx"

    def write(self, spec: ArtifactSpec, path: Path, style: ArtifactStyle) -> Path:
        from openpyxl import Workbook
        from openpyxl.styles import Alignment, Font, PatternFill

        wb = Workbook()
        ws = wb.active
        ws.title = (spec.sheet_name or "Data")[:31]

        if spec.headers:
            ws.append(spec.headers)
            fill = PatternFill("solid", fgColor=style.header_fill_hex)
            font = Font(bold=True, color=style.header_font_hex)
            for cell in ws[1]:
                cell.fill = fill
                cell.font = font
                cell.alignment = Alignment(horizontal="center")
            ws.freeze_panes = "A2"

        for row in spec.rows:
            ws.append(list(row))

        # Readable column widths from content length, bounded by the style.
        for idx, _ in enumerate(spec.headers or [], start=1):
            longest = max(
                [len(str(spec.headers[idx - 1]))]
                + [len(str(r[idx - 1])) for r in spec.rows if idx - 1 < len(r)],
                default=style.min_col_width,
            )
            width = max(style.min_col_width, min(style.max_col_width, longest + 2))
            ws.column_dimensions[ws.cell(row=1, column=idx).column_letter].width = width

        path.parent.mkdir(parents=True, exist_ok=True)
        wb.save(str(path))
        return path


_GENERATORS: dict[str, ArtifactGenerator] = {
    "pptx": PptxArtifactGenerator(),
    "docx": DocxArtifactGenerator(),
    "xlsx": XlsxArtifactGenerator(),
}


def get_generator(kind: str) -> ArtifactGenerator | None:
    return _GENERATORS.get(kind)
