# File: backend/app/artifacts/generators.py
"""
Real artifact generators — produce actual .pptx/.docx/.xlsx files on disk.

Each generator is an adapter over one office library (python-pptx, python-docx,
openpyxl) consuming the library-agnostic ArtifactSpec. Adding a new format
later means adding a generator + registry entry; nothing else changes.

Correctness first: clean, structurally valid files. Richer styling, images,
and templates are deliberately left as future extensions.
"""

from __future__ import annotations

from pathlib import Path
from typing import Protocol

from app.artifacts.spec import ArtifactSpec


class ArtifactGenerator(Protocol):
    kind: str

    def write(self, spec: ArtifactSpec, path: Path) -> Path: ...


class PptxArtifactGenerator:
    kind = "pptx"

    def write(self, spec: ArtifactSpec, path: Path) -> Path:
        from pptx import Presentation
        from pptx.util import Pt

        prs = Presentation()
        if spec.slides:
            # Title slide from the first spec slide.
            first = spec.slides[0]
            layout = prs.slide_layouts[0]
            slide = prs.slides.add_slide(layout)
            slide.shapes.title.text = first.title or spec.title
            if len(slide.placeholders) > 1:
                slide.placeholders[1].text = "Generated by AIRA-X"

            # Content slides.
            content_layout = prs.slide_layouts[1]
            for s in spec.slides[1:]:
                cslide = prs.slides.add_slide(content_layout)
                cslide.shapes.title.text = s.title
                body = cslide.placeholders[1].text_frame
                body.clear()
                bullets = s.bullets or [""]
                for i, bullet in enumerate(bullets):
                    para = body.paragraphs[0] if i == 0 else body.add_paragraph()
                    para.text = bullet
                    para.font.size = Pt(18)

        path.parent.mkdir(parents=True, exist_ok=True)
        prs.save(str(path))
        return path


class DocxArtifactGenerator:
    kind = "docx"

    def write(self, spec: ArtifactSpec, path: Path) -> Path:
        from docx import Document

        doc = Document()
        doc.add_heading(spec.title, level=0)
        for section in spec.sections:
            if section.heading:
                doc.add_heading(section.heading, level=1)
            for paragraph in section.paragraphs:
                doc.add_paragraph(paragraph)

        path.parent.mkdir(parents=True, exist_ok=True)
        doc.save(str(path))
        return path


class XlsxArtifactGenerator:
    kind = "xlsx"

    def write(self, spec: ArtifactSpec, path: Path) -> Path:
        from openpyxl import Workbook
        from openpyxl.styles import Font

        wb = Workbook()
        ws = wb.active
        ws.title = (spec.sheet_name or "Sheet1")[:31]

        if spec.headers:
            ws.append(spec.headers)
            for cell in ws[1]:
                cell.font = Font(bold=True)
        for row in spec.rows:
            ws.append(list(row))

        path.parent.mkdir(parents=True, exist_ok=True)
        wb.save(str(path))
        return path


_GENERATORS: dict[str, ArtifactGenerator] = {
    "pptx": PptxArtifactGenerator(),
    "docx": DocxArtifactGenerator(),
    "xlsx": XlsxArtifactGenerator(),
}


def get_generator(kind: str) -> ArtifactGenerator | None:
    return _GENERATORS.get(kind)
