# File: backend/app/artifacts/generators.py
"""
Real artifact generators — produce actual .pptx/.docx/.xlsx files on disk.

Each generator is an adapter over one office library (python-pptx, python-docx,
openpyxl) consuming the library-agnostic ArtifactSpec and a resolved theme
(ArtifactStyle). All formatting comes from the theme, so richer presets land
without touching generation logic. Correctness first: every styling step is
applied defensively (best-effort, guarded) so polish can never make generation
fragile, and validation still proves the file is real.
"""

from __future__ import annotations

from pathlib import Path
from typing import Protocol

from app.artifacts.images import resolve_image
from app.artifacts.spec import ArtifactSpec
from app.artifacts.styles import ArtifactStyle, get_style


class ArtifactGenerator(Protocol):
    kind: str

    def write(self, spec: ArtifactSpec, path: Path, style: ArtifactStyle) -> Path: ...


class PptxArtifactGenerator:
    kind = "pptx"

    def write(self, spec: ArtifactSpec, path: Path, style: ArtifactStyle) -> Path:
        from pptx import Presentation
        from pptx.dml.color import RGBColor
        from pptx.util import Inches, Pt

        prs = Presentation()
        accent = RGBColor(*style.accent_rgb)
        heading = RGBColor(*style.heading_rgb)
        body_color = RGBColor(*style.body_rgb)
        subtitle_color = RGBColor(*style.subtitle_rgb)

        for slide in spec.slides:
            layout = slide.layout

            if layout == "title":
                s = prs.slides.add_slide(prs.slide_layouts[0])
                self._paint_background(s, style)
                s.shapes.title.text = slide.title or spec.title
                self._style_title(s.shapes.title, style.title_size_pt, accent, style.title_font)
                if len(s.placeholders) > 1:
                    s.placeholders[1].text = slide.bullets[0] if slide.bullets else "Generated by AIRA-X"
                    self._style_text(s.placeholders[1], 20, subtitle_color, style.body_font, italic=True)
                continue

            if layout == "section":
                s = prs.slides.add_slide(prs.slide_layouts[2])
                self._paint_background(s, style)
                s.shapes.title.text = slide.title
                self._style_title(s.shapes.title, style.section_size_pt, accent, style.title_font)
                continue

            # agenda / content / summary use the title+content layout.
            s = prs.slides.add_slide(prs.slide_layouts[1])
            self._paint_background(s, style)
            s.shapes.title.text = slide.title
            self._style_title(s.shapes.title, style.slide_title_size_pt, heading, style.title_font)

            # Optional image: inserted only if a real local path resolved. Record
            # the resolved path back on the slide so usage can be reported.
            image_path = slide.image_path or resolve_image(slide.image_query)
            placed = False
            if image_path:
                try:
                    s.shapes.add_picture(image_path, Inches(6.6), Inches(1.8), width=Inches(3.0))
                    placed = True
                except Exception:
                    placed = False  # never let a bad image break the slide
            slide.image_path = image_path if placed else None

            body = s.placeholders[1].text_frame
            body.clear()
            body.word_wrap = True
            bullets = slide.bullets[: style.max_bullets_per_slide] or [""]
            for i, bullet in enumerate(bullets):
                para = body.paragraphs[0] if i == 0 else body.add_paragraph()
                para.text = bullet
                para.space_after = Pt(10)
                for run in para.runs:
                    run.font.size = Pt(style.body_size_pt)
                    run.font.name = style.body_font
                    try:
                        run.font.color.rgb = body_color
                    except Exception:
                        pass

        path.parent.mkdir(parents=True, exist_ok=True)
        prs.save(str(path))
        return path

    @staticmethod
    def _paint_background(slide, style: ArtifactStyle) -> None:
        if not style.dark or not style.background_rgb:
            return
        try:
            from pptx.dml.color import RGBColor

            fill = slide.background.fill
            fill.solid()
            fill.fore_color.rgb = RGBColor(*style.background_rgb)
        except Exception:
            pass  # background is best-effort; never break the slide

    @staticmethod
    def _style_title(shape, size_pt, color, font_name) -> None:
        from pptx.util import Pt

        try:
            for para in shape.text_frame.paragraphs:
                para.font.size = Pt(size_pt)
                para.font.bold = True
                para.font.name = font_name
                para.font.color.rgb = color
        except Exception:
            pass  # styling is best-effort; never break generation

    @staticmethod
    def _style_text(placeholder, size_pt, color, font_name, *, italic=False) -> None:
        from pptx.util import Pt

        try:
            for para in placeholder.text_frame.paragraphs:
                para.font.size = Pt(size_pt)
                para.font.italic = italic
                para.font.name = font_name
                para.font.color.rgb = color
        except Exception:
            pass


class DocxArtifactGenerator:
    kind = "docx"

    def write(self, spec: ArtifactSpec, path: Path, style: ArtifactStyle) -> Path:
        from datetime import date

        from docx import Document
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.shared import Pt, RGBColor

        doc = Document()
        accent = RGBColor(*style.accent_rgb)
        subtitle_color = RGBColor(*style.subtitle_rgb)

        # ── Title block ──────────────────────────────────────────────────────
        title = doc.add_heading(spec.title, level=0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        self._color_runs(title, accent)
        if spec.subtitle:
            sub = doc.add_paragraph(spec.subtitle)
            sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
            for run in sub.runs:
                run.italic = True
                run.font.size = Pt(13)
                self._safe_color(run, subtitle_color)
        # Subtle prepared-by metadata line.
        meta = doc.add_paragraph(f"Prepared by AIRA-X · {date.today().isoformat()}")
        meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
        for run in meta.runs:
            run.font.size = Pt(9)
            self._safe_color(run, subtitle_color)

        # ── Body sections ────────────────────────────────────────────────────
        for section in spec.sections:
            if section.heading:
                level = min(section.level, 2) or 1
                h = doc.add_heading(section.heading, level=level)
                self._color_runs(h, accent)
            for paragraph in section.paragraphs:
                p = doc.add_paragraph(paragraph)
                p.paragraph_format.space_after = Pt(8)
                for run in p.runs:
                    run.font.name = style.body_font
            for bullet in section.bullets:
                doc.add_paragraph(bullet, style="List Bullet")

        path.parent.mkdir(parents=True, exist_ok=True)
        doc.save(str(path))
        return path

    @staticmethod
    def _color_runs(paragraph, color) -> None:
        try:
            for run in paragraph.runs:
                run.font.color.rgb = color
        except Exception:
            pass

    @staticmethod
    def _safe_color(run, color) -> None:
        try:
            run.font.color.rgb = color
        except Exception:
            pass


class XlsxArtifactGenerator:
    kind = "xlsx"

    def write(self, spec: ArtifactSpec, path: Path, style: ArtifactStyle) -> Path:
        from openpyxl import Workbook
        from openpyxl.styles import Alignment, Font, PatternFill

        wb = Workbook()
        ws = wb.active
        ws.title = (spec.sheet_name or "Data")[:31]

        if spec.headers:
            ws.append(spec.headers)
            fill = PatternFill("solid", fgColor=style.header_fill_hex)
            font = Font(bold=True, color=style.header_font_hex)
            for cell in ws[1]:
                cell.fill = fill
                cell.font = font
                cell.alignment = Alignment(horizontal="center", vertical="center")
            ws.freeze_panes = "A2"

        zebra = (
            PatternFill("solid", fgColor=style.zebra_fill_hex)
            if style.zebra_fill_hex
            else None
        )
        for offset, row in enumerate(spec.rows):
            ws.append(list(row))
            if zebra and offset % 2 == 1:  # stripe every other data row
                excel_row = offset + 2  # +1 header, +1 to 1-based
                for cell in ws[excel_row]:
                    cell.fill = zebra

        # A clean autofilter over the header row aids real-world use.
        if spec.headers and spec.rows:
            try:
                last_col = ws.cell(row=1, column=len(spec.headers)).column_letter
                ws.auto_filter.ref = f"A1:{last_col}{len(spec.rows) + 1}"
            except Exception:
                pass

        # Readable column widths from content length, bounded by the theme.
        for idx, _ in enumerate(spec.headers or [], start=1):
            longest = max(
                [len(str(spec.headers[idx - 1]))]
                + [len(str(r[idx - 1])) for r in spec.rows if idx - 1 < len(r)],
                default=style.min_col_width,
            )
            width = max(style.min_col_width, min(style.max_col_width, longest + 2))
            ws.column_dimensions[ws.cell(row=1, column=idx).column_letter].width = width

        path.parent.mkdir(parents=True, exist_ok=True)
        wb.save(str(path))
        return path


_GENERATORS: dict[str, ArtifactGenerator] = {
    "pptx": PptxArtifactGenerator(),
    "docx": DocxArtifactGenerator(),
    "xlsx": XlsxArtifactGenerator(),
}


def get_generator(kind: str) -> ArtifactGenerator | None:
    return _GENERATORS.get(kind)
